# Generated by Django 3.2.12 on 2022-11-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0002_auto_20221031_1159'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankName',
            new_name='Bank',
        ),
    ]
