# Generated by Django 3.2.4 on 2022-08-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='bankname',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complaintype',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profiletype',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viewstatus',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workcategory',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
