# Generated by Django 3.2.4 on 2022-08-22 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20220822_1727'),
        ('projects', '0002_alter_project_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.category'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='configuration.category'),
        ),
    ]
