# Generated by Django 3.2.12 on 2022-11-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20221110_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
