# Generated by Django 3.2.12 on 2022-11-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_estimate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
