# Generated by Django 3.2.4 on 2022-08-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankname',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
