# Generated by Django 3.2.4 on 2022-08-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_auto_20220824_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='symbol',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='complaintype',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profiletype',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='viewstatus',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
