# Generated by Django 4.1.4 on 2022-12-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_cardtransfer_transaction_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtransfer',
            name='shaba',
            field=models.CharField(default='', max_length=24),
        ),
    ]
