# Generated by Django 4.2.5 on 2023-10-17 07:39

from django.db import migrations, models
import money.models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0008_alter_transaction_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardtransfer",
            name="tracking_code",
            field=models.IntegerField(blank=True, default=money.models.random_integer),
        ),
    ]
