# Generated by Django 4.2.5 on 2023-10-17 09:38

from django.db import migrations, models
import money.models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0009_cardtransfer_tracking_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardtransfer",
            name="tracking_code",
            field=models.IntegerField(
                blank=True, default=money.models.random_integer, null=True
            ),
        ),
    ]
