# Generated by Django 4.2.5 on 2023-10-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0010_alter_cardtransfer_tracking_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardtransfer",
            name="tracking_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
