# Generated by Django 3.2.12 on 2022-12-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time', models.IntegerField()),
                ('optional', models.BooleanField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculate_cost', models.IntegerField()),
                ('pay_cost', models.IntegerField()),
                ('pay_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_level', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('promotion', models.IntegerField()),
                ('description', models.TextField()),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OfferLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time', models.IntegerField()),
                ('optional', models.BooleanField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('exp_time', models.TimeField()),
                ('description', models.TextField()),
                ('budget_min', models.IntegerField()),
                ('budget_max', models.IntegerField()),
                ('tag', models.TextField()),
                ('cre_price', models.IntegerField()),
                ('budget_total', models.IntegerField()),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('discount', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.currency')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.level')),
            ],
        ),
    ]
