# Generated by Django 3.2 on 2022-10-31 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_party'),
        ('configuration', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='offer',
            name='party',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.party'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='party',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.party'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='skill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='configuration.skill'),
            preserve_default=False,
        ),
    ]
