# Generated by Django 3.2.12 on 2022-12-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('projects', '0001_initial'),
        ('location', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.party'),
        ),
        migrations.AddField(
            model_name='project',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.place'),
        ),
        migrations.AddField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(to='configuration.Skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.state'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.status'),
        ),
        migrations.AddField(
            model_name='offerlevel',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.offer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.party'),
        ),
        migrations.AddField(
            model_name='offer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='cost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.currency'),
        ),
        migrations.AddField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
