# Generated by Django 3.2.4 on 2022-08-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='applicant',
            new_name='project',
        ),
    ]
