# Generated by Django 3.2.4 on 2022-08-27 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_auto_20220824_0940'),
        ('projects', '0004_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.currency'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='offerlevel',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.currency'),
        ),
        migrations.AlterField(
            model_name='project',
            name='exp_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='work',
            field=models.CharField(max_length=255),
        ),
    ]
