# Generated by Django 3.2.12 on 2022-12-14 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('projects', '0005_auto_20221214_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='party',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.party'),
            preserve_default=False,
        ),
    ]
