# Generated by Django 3.2.12 on 2022-12-19 18:03

from django.db import migrations, models
import django.utils.timezone
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_merge_20221219_1047'),
        ('projects', '0010_alter_project_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offer',
            name='duration',
            field=models.DurationField(default=timedelta),
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='offer',
            name='state',
            field=models.CharField(blank=True, choices=[('a', 'Accept'), ('r', 'Reject'), ('n', 'Not Set')], default='n', max_length=1, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('project', 'party')},
        ),
        migrations.RemoveField(
            model_name='offer',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='total_level',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='total_time',
        ),
    ]
