# Generated by Django 3.2.12 on 2022-12-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20221219_1803'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfferLevel',
            new_name='OfferStep',
        ),
    ]
