# Generated by Django 4.1.4 on 2023-01-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_offer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='offerstep',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offersteps', to='projects.offer'),
        ),
    ]
