# Generated by Django 3.2.12 on 2022-12-14 17:37

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_category_parent'),
        ('projects', '0004_auto_20221214_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='project_file',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.File.hash_upload),
        ),
        migrations.AlterField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(to='configuration.Skill'),
        ),
    ]
