# Generated by Django 3.2.12 on 2022-12-14 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('configuration', '0002_alter_category_parent'),
        ('projects', '0006_file_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_city', to='location.city'),
        ),
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_country', to='location.country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_currency', to='configuration.currency'),
        ),
        migrations.AlterField(
            model_name='project',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_status', to='configuration.level'),
        ),
        migrations.AlterField(
            model_name='project',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_place', to='location.place'),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_state', to='location.state'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_status', to='configuration.status'),
        ),
    ]
