# Generated by Django 3.2.12 on 2022-12-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20221215_0854'),
        ('projects', '0009_alter_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(related_name='project_skill', to='configuration.Skill'),
        ),
    ]
