# Generated by Django 3.2.12 on 2022-12-21 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20221221_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='projects.project'),
        ),
    ]
