# Generated by Django 3.2.12 on 2022-12-21 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_merge_20221219_1047'),
        ('projects', '0015_alter_budget_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerstep',
            name='party',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.party'),
            preserve_default=False,
        ),
    ]
