# Generated by Django 4.1.4 on 2023-02-01 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_budget_project_alter_offer_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='exp_time',
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
