# Generated by Django 4.1.4 on 2023-04-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_file_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'New'), ('i', 'In Progress'), ('c', 'Closed')], default='n', max_length=1, null=True),
        ),
    ]
