# Generated by Django 4.1.5 on 2023-07-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_alter_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="comment",
            field=models.TextField(default=""),
        ),
    ]
