# Generated by Django 4.2.5 on 2023-10-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0022_file_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="create_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="is_last_file",
            field=models.BooleanField(default=False),
        ),
    ]
