# Generated by Django 4.2.5 on 2023-11-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0005_alter_skill_name"),
        ("projects", "0024_alter_project_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="skill",
            field=models.ManyToManyField(
                related_name="project_skill", to="configuration.skill"
            ),
        ),
    ]
