# Generated by Django 4.2.5 on 2024-02-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_alter_project_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offerstep',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
