# Generated by Django 4.1.4 on 2023-01-08 09:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_offer_state'),
        ('user', '0012_alter_education_degree'),
        ('chat', '0002_remove_message_source_message_party_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='project',
        ),
        migrations.RemoveField(
            model_name='message',
            name='target',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archived', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='user.party')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participate', to='user.party')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participate', to='chat.room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='chat.room'),
            preserve_default=False,
        ),
    ]
