# Generated by Django 4.1.4 on 2023-01-08 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_education_degree'),
        ('chat', '0005_remove_room_archived_participate_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chat_user', to='user.party'),
            preserve_default=False,
        ),
    ]
