# Generated by Django 4.2.5 on 2023-10-15 07:28

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_alter_room_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="media",
            field=models.FileField(
                blank=True, null=True, upload_to=chat.models.Message.hash_upload
            ),
        ),
    ]
