# Generated by Django 4.2.5 on 2023-11-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_remove_message_is_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
