# Generated by Django 4.1.4 on 2022-12-31 08:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_merge_20221219_1047'),
        ('money', '0003_alter_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.BigIntegerField(default=0)),
                ('shaba', models.BigIntegerField(default=0)),
                ('value', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.party')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='money.cardtransfer'),
        ),
    ]
