# Generated by Django 4.1.4 on 2023-01-15 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_education_degree'),
        ('money', '0006_cardtransfer_state_cardtransfer_transfered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='user.party'),
        ),
    ]
