# Generated by Django 4.2.5 on 2023-11-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0004_status_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
