# Generated by Django 4.2.5 on 2024-02-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_alter_skill_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('type', 'name')},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('category__name', 'id')},
        ),
    ]
