# Generated by Django 3.2.12 on 2022-12-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='education',
            name='uni_name',
            field=models.TextField(default=''),
        ),
    ]
