# Generated by Django 3.2.12 on 2022-12-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_merge_0007_auto_20221217_1055_0007_auto_20221217_1636'),
        ('user', '0008_worksample_work_file'),
    ]

    operations = [
    ]
