# Generated by Django 3.2.12 on 2022-12-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20221219_0833'),
        ('user', '0010_remove_experience_skill'),
    ]

    operations = [
    ]
