# Generated by Django 4.1.4 on 2023-03-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_education_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
    ]
