# Generated by Django 4.1.5 on 2023-07-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_profile_is_employer"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="company_name",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="opinion",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
