# Generated by Django 4.1.5 on 2023-08-14 12:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0004_status_default"),
        ("user", "0014_profile_company_name_vote_opinion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilePermissions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_permission",
                        to="configuration.category",
                    ),
                ),
                (
                    "party",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_party",
                        to="user.party",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
