# Generated by Django 4.1.5 on 2023-08-14 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0004_status_default"),
        ("user", "0016_alter_profilepermissions_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilepermissions",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_permission",
                to="configuration.category",
            ),
        ),
        migrations.AlterField(
            model_name="profilepermissions",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_party",
                to="user.party",
            ),
        ),
    ]
