# Generated by Django 4.1.5 on 2023-08-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_alter_profilepermissions_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilepermissions",
            name="party",
        ),
        migrations.AddField(
            model_name="profilepermissions",
            name="profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="user.profile",
            ),
            preserve_default=False,
        ),
    ]
