# Generated by Django 4.1.5 on 2023-08-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_remove_profilepermissions_party_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilepermissions",
            name="profile",
        ),
        migrations.AddField(
            model_name="profilepermissions",
            name="party",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="party_permission",
                to="user.party",
            ),
            preserve_default=False,
        ),
    ]
