# Generated by Django 4.1.5 on 2023-08-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_remove_profilepermissions_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="date_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
