# Generated by Django 4.2.5 on 2023-10-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0020_alter_education_date_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
    ]
