# Generated by Django 4.2.5 on 2023-10-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0021_alter_profile_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vote_party",
                to="user.party",
            ),
        ),
    ]
