# Generated by Django 4.2.5 on 2023-10-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0022_alter_vote_party"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vote_owner",
                to="user.party",
            ),
        ),
    ]
