# Generated by Django 4.1.4 on 2023-01-08 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_offer_state'),
        ('chat', '0004_message_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='archived',
        ),
        migrations.AddField(
            model_name='participate',
            name='archived',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
