# Generated by Django 4.1.4 on 2023-01-15 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_budget_project_alter_offer_project_and_more'),
        ('chat', '0006_room_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='projects.project'),
        ),
    ]
