# Generated by Django 3.2.4 on 2022-07-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
