# Generated by Django 3.2.4 on 2022-07-20 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('vacancy', '0002_vacancy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='budget_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='time_estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.estimate'),
        ),
    ]
