# Generated by Django 3.2.4 on 2022-07-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_auto_20220720_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('time', models.IntegerField()),
                ('optional', models.BooleanField()),
                ('cost', models.IntegerField()),
                ('Applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.applicant')),
            ],
        ),
    ]
