# Generated by Django 3.2.12 on 2022-07-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_applicantlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
