# Generated by Django 3.2.12 on 2022-12-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('exp_opinion', models.TextField(null=True)),
                ('complain_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.complaintype')),
            ],
        ),
        migrations.CreateModel(
            name='ResultComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('resulte', models.TextField()),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain.complain')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.status')),
            ],
        ),
    ]
