# Generated by Django 3.2.12 on 2022-12-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('configuration', '0001_initial'),
        ('complain', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complain_owner', to='user.party'),
        ),
        migrations.AddField(
            model_name='complain',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='complain',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complain_user', to='user.party'),
        ),
        migrations.AddField(
            model_name='complain',
            name='viewstatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.viewstatus'),
        ),
    ]
