# Generated by Django 3.2.12 on 2022-12-14 14:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('pos', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.IntegerField()),
                ('de_wi', models.CharField(blank=True, choices=[('d', 'Deposit'), ('w', 'withdraw')], default='d', max_length=1, null=True)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheba', models.CharField(max_length=26, unique=True)),
                ('card', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('transaction', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('transaction', models.IntegerField()),
                ('to_account', models.IntegerField()),
                ('acc_name', models.CharField(max_length=255)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='count.count')),
            ],
        ),
    ]
