# Generated by Django 3.2.4 on 2022-08-22 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheba', models.TextField()),
                ('card', models.TextField()),
                ('name', models.TextField()),
                ('bankname', models.TextField()),
                ('active', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('transaction', models.TextField()),
                ('to_account', models.IntegerField()),
                ('acc_name', models.TextField()),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='count.count')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('transaction', models.TextField()),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='count.count')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_acc', models.TextField()),
                ('email', models.TextField()),
                ('name', models.TextField()),
                ('pos', models.TextField()),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('de_wi', models.CharField(blank=True, choices=[('d', 'Deposit'), ('w', 'withdraw')], default='m', max_length=1, null=True)),
                ('balance', models.IntegerField()),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='count.count')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
