# Generated by Django 3.2 on 2022-10-31 08:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_party'),
        ('configuration', '0001_initial'),
        ('count', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='count',
            name='user',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='party',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.party'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='count',
            name='party',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.party'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposit',
            name='party',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.party'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw',
            name='party',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.party'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='count',
            name='bankname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.bankname'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
