# Generated by Django 3.2.4 on 2022-08-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='de_wi',
            field=models.CharField(blank=True, choices=[('d', 'Deposit'), ('w', 'withdraw')], default='d', max_length=1, null=True),
        ),
    ]
