# Generated by Django 3.2.4 on 2022-08-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0002_alter_account_de_wi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id_acc',
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='pos',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='count',
            name='bankname',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='count',
            name='card',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='count',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='count',
            name='sheba',
            field=models.CharField(max_length=26, unique=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='transaction',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='acc_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='transaction',
            field=models.IntegerField(),
        ),
    ]
