# Generated by Django 3.2.12 on 2022-10-22 07:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '__first__'),
        ('configuration', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_date', models.DateTimeField(default=datetime.datetime.now)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_owner', to='user.party')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.party')),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configuration.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vot', models.IntegerField(blank=True, default=0, null=True)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='party', to='user.party')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='user.party')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('level', models.TextField()),
                ('description', models.TextField()),
                ('Institution_name', models.TextField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.party')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('userid', models.TextField()),
                ('phone', models.TextField()),
                ('link', models.TextField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.party')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configuration.level')),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.party')),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configuration.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('gender', models.CharField(blank=True, choices=[('f', 'Female'), ('m', 'Male')], default='m', max_length=1, null=True)),
                ('marital', models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], default='m', max_length=1, null=True)),
                ('vote_total', models.IntegerField(blank=True, default=0, null=True)),
                ('panel', models.IntegerField(blank=True, default=0, null=True)),
                ('panel_timeout', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('news', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.country')),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.party')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.state')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talking', models.IntegerField(blank=True, default=0, null=True)),
                ('writing', models.IntegerField(blank=True, default=0, null=True)),
                ('comprehension', models.IntegerField(blank=True, default=0, null=True)),
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configuration.language')),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.party')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('company', models.TextField()),
                ('description', models.TextField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.party')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.TextField()),
                ('description', models.TextField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('degree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configuration.degree')),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.party')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(blank=True, choices=[('p', 'Phone'), ('m', 'Mobile'), ('a', 'Address')], default='a', max_length=1, null=True)),
                ('contact', models.TextField()),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.party')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('Institution_name', models.TextField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.party')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('event', models.TextField()),
                ('description', models.TextField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.party')),
            ],
        ),
    ]
