# Generated by Django 3.2.12 on 2022-10-24 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_party_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(blank=True, default=0, null=True)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote_party', to='user.party')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote_owner', to='user.party')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='party',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='party', to='user.party'),
        ),
        migrations.DeleteModel(
            name='Voting',
        ),
    ]
