# Generated by Django 3.2.12 on 2022-12-15 14:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20221215_0854'),
        ('user', '0003_auto_20221215_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_experience', to='user.party')),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configuration.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
