# Generated by Django 3.2.12 on 2022-10-24 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('user', '0003_auto_20221024_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='voter',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.party'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.party'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.party'),
        ),
        migrations.AlterField(
            model_name='education',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.party'),
        ),
        migrations.AlterField(
            model_name='job',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.party'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.language', unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.party'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.level'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.party'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.skill'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.party'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.party'),
        ),
    ]
