# Generated by Django 3.2.12 on 2022-10-24 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('user', '0004_auto_20221024_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.language'),
        ),
    ]
