# Generated by Django 3.2.8 on 2022-12-17 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='date_end',
            field=models.DateTimeField(default=datetime.date(2022, 12, 17)),
        ),
        migrations.AddField(
            model_name='experience',
            name='date_start',
            field=models.DateTimeField(default=datetime.date(2022, 12, 17)),
        ),
        migrations.AddField(
            model_name='experience',
            name='work_place',
            field=models.TextField(default=''),
        ),
    ]
