# Generated by Django 3.2.12 on 2022-10-31 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_party_deleted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_skill', to='user.party'),
        ),
    ]
