# Generated by Django 3.2.8 on 2022-12-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20221217_1055'),
        ('user', '0007_auto_20221217_1636'),
    ]

    operations = [
    ]
