# Generated by Django 3.2.12 on 2022-10-31 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_skill_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='party',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='party_profile', to='user.party'),
        ),
    ]
