# Generated by Django 3.2.8 on 2022-12-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_merge_0007_auto_20221217_1055_0007_auto_20221217_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='work_place',
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
