# Generated by Django 3.2.12 on 2022-10-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('user', '0008_alter_profile_party'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('party', 'skill')},
        ),
    ]
