# Generated by Django 3.2 on 2022-11-02 06:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('user', '0008_alter_profile_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='deleted_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='party',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='party', to='user.party'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.party'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_set', to='configuration.skill'),
        ),
    ]
