# Generated by Django 3.2.12 on 2022-11-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_skill_unique_together'),
        ('user', '0009_auto_20221102_0937'),
    ]

    operations = [
    ]
