# Generated by Django 3.2.12 on 2022-11-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_rename_bankname_bank'),
        ('user', '0010_merge_20221109_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='party',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='party_profile', to='user.party'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_skill', to='user.party'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.skill'),
        ),
    ]
