# Generated by Django 4.1.4 on 2023-01-07 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20221215_0854'),
        ('user', '0011_merge_20221219_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.degree'),
        ),
    ]
