# Generated by Django 3.2.12 on 2022-11-10 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20221109_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_achievement', to='user.party'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_certificate', to='user.party'),
        ),
        migrations.AlterField(
            model_name='education',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_education', to='user.party'),
        ),
        migrations.AlterField(
            model_name='job',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_job', to='user.party'),
        ),
        migrations.AlterField(
            model_name='language',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_language', to='user.party'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_socialmedia', to='user.party'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_sceciality', to='user.party'),
        ),
        migrations.AlterField(
            model_name='worksample',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_worksample', to='user.party'),
        ),
    ]
