# Generated by Django 3.2.12 on 2022-11-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20221110_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_speciality', to='user.party'),
        ),
    ]
