# Generated by Django 3.2.12 on 2022-12-05 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 6, 23, 11, 469641)),
        ),
    ]
