# Generated by Django 3.2.12 on 2022-12-06 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20221205_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='activated_at',
        ),
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 6, 36, 34, 149684)),
        ),
    ]
