# Generated by Django 3.2.12 on 2022-12-06 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 8, 8, 31, 23741)),
        ),
    ]
