# Generated by Django 3.2.12 on 2022-12-08 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20221208_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 14, 35, 58, 464517)),
        ),
    ]
