# Generated by Django 3.2.12 on 2022-12-08 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20221208_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 14, 49, 47, 344013)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='party',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='party_profile', serialize=False, to='user.party'),
        ),
    ]
