# Generated by Django 3.2.12 on 2022-12-12 08:27

from django.db import migrations, models
import django.utils.timezone
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20221208_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/home/mostafa/Programs/python/mitco/midlancer/midlancer-back/media')),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
