# Generated by Django 3.2.12 on 2022-12-12 10:25

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20221212_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_contact', to='user.party'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.Profile.hash_upload),
        ),
    ]
