name: Midlancer 
                               
on:
  push:
    branches-ignore: ["main", "master"]
permissions:
  contents: write
  pull-requests: write

jobs:
  syntax_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3   
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies    
      run: |
        python -m pip install --upgrade pip
        pip install -r ../requirements.txt 
        pip install pylint pylint-django
      working-directory: ./backend
    - name: Analysing the code with pylint
      run: |
        pylint --load-plugins pylint_django --fail-under=9 --django-settings-module=midlancer.settings  midlancer/urls.py
      working-directory: ./backend
  test:
    needs: syntax_check 
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ../requirements.txt
      working-directory: ./backend

  pull-request:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
  deploy-test-server:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 176.97.218.196
        username: 'root'
        password: '!@#$FGHJpoqs'
        port: 22
        script: 
          cd /opt/
          rm -rf midlancer-back/
          git clone https://github.com/salimzadeh/midlancer-back.git
          cd midlancer-back/backend/
          python managepy runserver
